# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0a0ef6d6c2ffa9c64891c2cb0b7dca146eedac658edd0be3f53769a2429ecc3957c5cd1b2fcf9ee45bd35dc5e34f1a4f707b7615f63bf93e739d58ace6a8f320

test:
  secret_key_base: 397a36718e0a302e6522985b2e405e8956e43f1137a7aa2518e73d93cf67365b13e01a641ea83e4ddb6acea37d827d633e24bc160488282a1969a0d8bea44f6a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
